package com.example.quizify.ui.screens

import android.content.Intent
import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import com.example.quizify.data.model.QuizResult
import com.example.quizify.ui.components.ReviewCard
import com.example.quizify.ui.theme.*
import com.example.quizify.utils.PerformanceTips
import kotlinx.coroutines.delay

@Composable
fun ResultScreen(
    result: QuizResult,
    onRetake: () -> Unit,
    onNewQuiz: () -> Unit
) {
    var visible by remember { mutableStateOf(false) }
    val scrollState = rememberScrollState()
    val context = LocalContext.current

    LaunchedEffect(Unit) {
        delay(300)
        visible = true
    }

    fun shareResult() {
        val emoji = when {
            result.scorePercentage >= 80 -> "🏆"
            result.scorePercentage >= 60 -> "👍"
            result.scorePercentage >= 40 -> "📚"
            else -> "💪"
        }
        val shareText = """
$emoji My Quiz Result — QuizGenie

📊 Score: ${"%.1f".format(result.scorePercentage)}%
✅ Correct: ${result.correctAnswers}/${result.totalQuestions}
❌ Wrong: ${result.wrongAnswers}
⏭️ Skipped: ${result.skippedAnswers}
⏱️ Time: ${formatTime(result.timeTakenSeconds)}

${when {
            result.scorePercentage >= 80 -> "Excellent performance! 🔥"
            result.scorePercentage >= 60 -> "Good job! Keep it up! 💪"
            result.scorePercentage >= 40 -> "Keep practicing! 📖"
            else -> "Don't give up! Try again! 🚀"
        }}

Generated by QuizGenie App 🎯
        """.trimIndent()

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, shareText)
            putExtra(Intent.EXTRA_SUBJECT, "My QuizGenie Result")
        }
        context.startActivity(Intent.createChooser(intent, "Share Result"))
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(BackgroundDark)
            .windowInsetsPadding(WindowInsets.systemBars)
            .verticalScroll(scrollState)
            .padding(20.dp)
    ) {
        AnimatedVisibility(
            visible = visible,
            enter = fadeIn(tween(800)) + slideInVertically(tween(800)) { it / 3 }
        ) {
            Column(
                modifier = Modifier.fillMaxWidth(),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(
                    text = getEmoji(result.scorePercentage),
                    fontSize = 64.sp,
                    modifier = Modifier.padding(bottom = 8.dp)
                )
                Text(
                    text = PerformanceTips.getMotivationalMessage(result.scorePercentage),
                    color = TextPrimary,
                    fontSize = 22.sp,
                    fontWeight = FontWeight.Bold,
                    textAlign = TextAlign.Center
                )
                Text(
                    text = "You completed the quiz in ${formatTime(result.timeTakenSeconds)}",
                    color = TextMuted,
                    fontSize = 14.sp,
                    textAlign = TextAlign.Center,
                    modifier = Modifier.padding(top = 8.dp, bottom = 20.dp)
                )
            }
        }

        AnimatedVisibility(
            visible = visible,
            enter = fadeIn(tween(1000, delayMillis = 300)) +
                    scaleIn(tween(1000, delayMillis = 300), initialScale = 0.5f)
        ) {
            Box(
                modifier = Modifier
                    .size(180.dp)
                    .padding(vertical = 10.dp)
                    .align(Alignment.CenterHorizontally),
                contentAlignment = Alignment.Center
            ) {
                Box(
                    modifier = Modifier
                        .fillMaxSize()
                        .clip(CircleShape)
                        .background(SurfaceDark)
                )
                CircularProgressIndicator(
                    progress = { result.scorePercentage / 100f },
                    modifier = Modifier.fillMaxSize(),
                    color = when {
                        result.scorePercentage >= 80 -> SuccessGreen
                        result.scorePercentage >= 60 -> PrimaryPurple
                        else -> WarningYellow
                    },
                    trackColor = Color.Transparent,
                    strokeWidth = 12.dp
                )
                Box(
                    modifier = Modifier
                        .size(140.dp)
                        .clip(CircleShape)
                        .background(BackgroundDark),
                    contentAlignment = Alignment.Center
                ) {
                    Text(
                        text = "${result.scorePercentage.toInt()}%",
                        color = TextPrimary,
                        fontSize = 40.sp,
                        fontWeight = FontWeight.ExtraBold
                    )
                }
            }
        }

        Spacer(modifier = Modifier.height(24.dp))

        AnimatedVisibility(
            visible = visible,
            enter = fadeIn(tween(1200, delayMillis = 500))
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                StatBox(
                    icon = Icons.Default.CheckCircle,
                    value = result.correctAnswers.toString(),
                    label = "Correct",
                    color = SuccessGreen,
                    modifier = Modifier.weight(1f)
                )
                StatBox(
                    icon = Icons.Default.Cancel,
                    value = result.wrongAnswers.toString(),
                    label = "Wrong",
                    color = ErrorRed,
                    modifier = Modifier.weight(1f)
                )
                StatBox(
                    icon = Icons.Default.RemoveCircle,
                    value = result.skippedAnswers.toString(),
                    label = "Skipped",
                    color = WarningYellow,
                    modifier = Modifier.weight(1f)
                )
            }
        }

        Spacer(modifier = Modifier.height(24.dp))

        AnimatedVisibility(
            visible = visible,
            enter = fadeIn(tween(1400, delayMillis = 700)) +
                    slideInVertically(tween(1400, delayMillis = 700)) { it / 4 }
        ) {
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = BackgroundCard),
                border = BorderStroke(1.dp, PrimaryPurple.copy(alpha = 0.3f)),
                shape = RoundedCornerShape(16.dp)
            ) {
                Column(modifier = Modifier.padding(18.dp)) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.Lightbulb,
                            contentDescription = null,
                            tint = PrimaryPurple,
                            modifier = Modifier.size(20.dp)
                        )
                        Text(
                            text = "AI Performance Tip",
                            color = PrimaryPurple,
                            fontSize = 15.sp,
                            fontWeight = FontWeight.SemiBold
                        )
                    }
                    Spacer(modifier = Modifier.height(10.dp))
                    Text(
                        text = result.aiTip,
                        color = TextSecondary,
                        fontSize = 14.sp,
                        lineHeight = 22.sp
                    )
                }
            }
        }

        Spacer(modifier = Modifier.height(24.dp))

        if (result.weakTopics.isNotEmpty()) {
            Text(
                text = "📚 Focus Areas",
                color = TextPrimary,
                fontSize = 18.sp,
                fontWeight = FontWeight.Bold,
                modifier = Modifier.padding(bottom = 12.dp)
            )
            LazyRow(
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                contentPadding = PaddingValues(horizontal = 24.dp)
            ) {
                items(result.weakTopics){ topic ->
                    WeakTopicChip(topic = topic)
                }
            }
            /*Row(
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                modifier = Modifier.padding(bottom = 24.dp)
            ) {
                result.weakTopics.forEach { topic ->
                    WeakTopicChip(topic = topic)
                }
            }*/
        }


        Text(
            text = "📝 Review Answers",
            color = TextPrimary,
            fontSize = 18.sp,
            fontWeight = FontWeight.Bold,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        result.questionResults.forEachIndexed { index, qr ->
            AnimatedVisibility(
                visible = visible,
                enter = fadeIn(tween(1500 + index * 100))
            ) {
                ReviewCard(
                    questionResult = qr,
                    modifier = Modifier.padding(bottom = 12.dp)
                )
            }
        }

        Spacer(modifier = Modifier.height(24.dp))

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            OutlinedButton(
                onClick = { shareResult() },
                modifier = Modifier
                    .weight(1f)
                    .height(56.dp),
                shape = RoundedCornerShape(16.dp),
                border = BorderStroke(1.dp, PrimaryPurple),
                colors = ButtonDefaults.outlinedButtonColors(
                    contentColor = PrimaryPurple
                )
            ) {
                Icon(
                    imageVector = Icons.Default.Share,
                    contentDescription = null,
                    modifier = Modifier.size(18.dp)
                )
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = "Share",
                    fontSize = 15.sp,
                    fontWeight = FontWeight.SemiBold
                )
            }

            Button(
                onClick = onRetake,
                modifier = Modifier
                    .weight(1f)
                    .height(56.dp),
                shape = RoundedCornerShape(16.dp),
                colors = ButtonDefaults.buttonColors(containerColor = Color.Transparent),
                contentPadding = PaddingValues(0.dp)
            ) {
                Box(
                    modifier = Modifier
                        .fillMaxSize()
                        .background(
                            Brush.horizontalGradient(listOf(PrimaryPurple, SecondaryViolet)),
                            RoundedCornerShape(16.dp)
                        ),
                    contentAlignment = Alignment.Center
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.Refresh,
                            contentDescription = null,
                            tint = TextPrimary,
                            modifier = Modifier.size(18.dp)
                        )
                        Text(
                            text = "Retake",
                            color = TextPrimary,
                            fontSize = 15.sp,
                            fontWeight = FontWeight.SemiBold
                        )
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(12.dp))

        OutlinedButton(
            onClick = onNewQuiz,
            modifier = Modifier
                .fillMaxWidth()
                .height(52.dp),
            shape = RoundedCornerShape(16.dp),
            border = BorderStroke(1.dp, BorderLight),
            colors = ButtonDefaults.outlinedButtonColors(contentColor = TextPrimary)
        ) {
            Icon(
                imageVector = Icons.Default.Add,
                contentDescription = null,
                modifier = Modifier.size(18.dp)
            )
            Spacer(modifier = Modifier.width(8.dp))
            Text("New Quiz")
        }

        Spacer(modifier = Modifier.height(32.dp))
    }
}

@Composable
private fun StatBox(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    value: String,
    label: String,
    color: Color,
    modifier: Modifier = Modifier
) {
    Column(
        modifier = modifier
            .clip(RoundedCornerShape(16.dp))
            .background(SurfaceDark)
            .padding(18.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Icon(
            imageVector = icon,
            contentDescription = null,
            tint = color,
            modifier = Modifier.size(28.dp)
        )
        Spacer(modifier = Modifier.height(10.dp))
        Text(text = value, color = color, fontSize = 24.sp, fontWeight = FontWeight.Bold)
        Text(text = label, color = TextMuted, fontSize = 11.sp, fontWeight = FontWeight.Medium)
    }
}

@Composable
private fun WeakTopicChip(topic: String) {
    Box(
        modifier = Modifier
            .clip(RoundedCornerShape(20.dp))
            .background(WarningYellow.copy(alpha = 0.15f))
            .border(1.dp, WarningYellow.copy(alpha = 0.3f), RoundedCornerShape(20.dp))
            .padding(horizontal = 14.dp, vertical = 8.dp)
    ) {
        Text(
            text = topic,
            color = WarningYellow,
            fontSize = 13.sp,
            fontWeight = FontWeight.Medium
        )
    }
}

private fun getEmoji(score: Float): String = when {
    score >= 90 -> "🏆"
    score >= 80 -> "🌟"
    score >= 70 -> "💪"
    score >= 60 -> "👍"
    score >= 50 -> "📈"
    score >= 40 -> "🎯"
    else -> "💪"
}

private fun formatTime(seconds: Long): String {
    val m = seconds / 60
    val s = seconds % 60
    return String.format("%02d:%02d", m, s)
}